[[main]]
    name = "ARCHIVES"
    weight = 60
[[main]]
    parent = "ARCHIVES"
    name = "PUBLICATIONS"
    url = "/archives/publications/"
    weight = 61

[[main]]
    parent = "ARCHIVES"
    name = "OFFICE HOURS"
     url = "/archives/officehours/"
    weight = 64
